baseURL: "https://sharanya510.github.io"
languageCode: "en-us"
title: "Sharanya Gandla"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true


markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # title: "Hugo Profile"
  # description: Text about my cool site
  # # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  # useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  # animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"

  # If you want to customize the menu, you can change it here
  navbar:
    position: absolute
    # align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: null  # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    disableSearch: true
    # # searchPlaceholder: "Search"
    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: false
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi there! I am "
    title: "Sharanya Gandla."
    subtitle: "Graduate student at San Jose State University"
    content: "A passionate graduate student who loves exploring latest technologies, building POCs and incorporating them into existing products.
    I really enjoy painting, baking and photography.
    I live in San Jose, California, USA."
    image: "/images/sharanya1.png"
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/10ysNqbWH2Ju29mrwAXoDFvoK22gw4FOH/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/sharanya510
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sharanya-gandla-4097a7188/
        

  # About
  about:
    enable: true
    title: "About"
    image: "/images/sharanya2.png"
    content: |-
     Currently looking for Full-time opportunities. Pursuing master's degree in Data Science with 3 years of professional experience as a Software Engineer at NCR Corporation, Hyderabad, India. 
     I have a strong interest in the the intersection of Technology and Business.
     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Programming Languages: C, C++, Python, Unix/Linux, GoLang, HTML, CSS, YAML, JSON, XML, Bash, Powershell, JavaScript"
        - "Databases: MySQL, Microsoft SQL server, MongoDB"
        - "Machine Learning Tools: Pandas, Numpy, TensorFlow, PyTorch, TensorFlow Serving, Sci-Kit learn, Keras"
        - "Tools and software: Jenkins, Terraform, Site 24x7, Sensu, Apigee, Rundeck, Docker, Kubernetes, Helm, Vault, Git, Github Actions, Chef, ArgoCD, Artifactory, Bitbucket, Postman, Kibana, Elastic Search, Matlab, Tableau, Grafana, Prometheus"
        - "Cloud: Microsoft Azure, GCP, AWS, Heroku"
        - "Leadership: Mentorship, Multi-Cultural Fluency, Team Player"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer II"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "Feb 2021 - Dec 2021"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Led and managed the Chef Upgrade project, migrated all cookbooks from Chef version 14 to 17.
          - Spearheaded the Migration from ARM to Terraform initiative across 6 products, increasing flexibility for deployment.
          - Deployed automation for globally patching and booting virtual machines on the Azure cloud, leading to a reduction of approximately 16 hours per week in time expended by the cloud team.
          - Executed a POC to establish a resilient Continuous Delivery(CD) pipeline employing ArgoCD v2.2.2 for automating deployments.

      - job: "Software Engineer I"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "July 2019 - Jan 2021"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Devised and put into practice an extensive process leveraging Apigee and GitHub Actions to manage traffic throughout the “Migration from on-premise to Azure” project.
          - NCRs food ordering operations achieved the capacity to accommodate 4 times the normal traffic load and process approximately 2 million transactions each day.
          - Migrated over 2,000 companies in flights by efficiently splitting traffic based on weights and percentages tailored to customer requirements, ensuring seamless transition during the migration process.
          - Researched on CINC, a highly efficient configuration management tool automating file management, data bags, and secret management, significantly reducing manual efforts and enhancing overall operational efficiency.
          - Utilized sensu monitoring tool with helm across 10 products, performing version control mechanism revamped efficiency by 20%.
          - Designed a synthetic monitoring system leveraging site 24x7, incorporating a selenium recorder to simulate User Flow and API functionality. Integrated with pagerduty for real-time notifications, reducing incident response time by 40%.
          - Created dashboards for multiple clients to notice the performance of the application during heavy traffic and peak time.

      - job: "Software Engineer Intern"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "May 2019 - June 2019"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Built customized dashboards for multiple clients to monitor application performance during high traffic periods. These dashboards increased visibility and allowed for proactive troubleshooting, resulting in a 15% reduction in system downtime.

      - job: "Software Trainee"
        company: "CDAC"
        companyUrl: "https://ncr.com"
        date: "Jan 2019 - April 2019"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Underwent a 10 week training program on software technologies like C, C++, DS, DBMS, SQL, windows, HTML, XML.

      - job: "Intern"
        company: "NFC"
        # companyUrl: "https://.com"
        date: "June 2018 - June 2018"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - One month internship program, where I have obtained great exposure towards the processes carried out at NFC and understanding of how do they actually make use of chemicals.
          - It was a wonderful opportunity to work on aproject titled "Monitoring temperature and humidity in a room" and gained practical exposure.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science"
        school:
          name: "San Jose State University"
          url: "https://sjsu.org"
        date: "2022 - 2023"
        GPA: "3.75 out of 4.0"
        content: |-
          Course Work
            - Data Structures & Algorithms
            - Data Mining
            - Enterprise Software Platforms
            - Business Intelligence Systems
            - AI and Data Engineering

      - title: "Bachelor of Engineering in Electronics and Communication"
        school:
          name: "Chaitanya Bharathi Institute of Technology"
          url: "https://cbit.org"
        date: "2015 - 2019"
        GPA: "9.2 out of 10.0"
        content: |-
          Extracurricular Activities
            - Been head of the Design team for the college fest over the period of 4 years.
            - Won multiple prizes in the art competition.
            

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: R&D Excellence award
        content: I was awarded R&D excellence award for the year 2020 for my work on the project Nolo Traffic Manager.
        
     

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Acceleration via Intel Optimization for PyTorch
        content: Demonstrated substantial performance improvement in “resnet50” image classification on the “Fashion MNIST” dataset by accelerating via Intel Optimization for PyTorch and Torchscript. Accomplished an impressive 94.6% reduction in models inference time. Effectively visualized the models performance logs on TensorBoard for comprehensive analysis.
        image: /images/acceleration.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/Acceleration_via_intel_optimization_for_pytorch

      - title: Twitter Sentiment Analysis
        content: Performed Sentiment Analysis with NLP where live tweets are extracted using Twitter API and pre-processed the tweets to classify tweets as positive, negative, and neutral with an LSTM model.
        image: /images/twitter.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/Twitter-sentiment-analysis

      - title: Multi Modal Classifier
        content: Developed a sequential multi-modal deep learning classifier utilizing the Fashion MNIST dataset, achieving a 91.72% accuracy. Successfully transformed the TensorFlow model into TensorFlow Lite format for optimized deployment and conducted inference. Implemented model serving using TensorFlow serving to ensure efficient and reliable predictions.
        image: /images/multimodal.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/MultiModalClassifier

      - title: House Price Prediction
        content: Constructed a regression model with the capability to precisely predict property rices through an analysis of their attributes. This process entailed comprehending the dataset, conducting Exploratory Data Analysis(EDA), crafting a Flask web application, and executing its deployment.
        image: /images/house.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/House_Price_Prediction
      
      - title: Mirror Assistant
        content: Created an application designed to enhance communication skills, particularly for interviews and presentations. This tool functions similar to a mirror, offering feedback on fillers and facial expressions to aid individuals in their practice.
        image: /images/mirror.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/MirrorAssistant
          
      - title: Smart Meter Management System
        content: Developed an application using MERN. Performed C.R.U.D operation on IoT devices. Generates bills in a building based on a pay-as-you-use model.
        image: /images/smartmeter.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/MirrorAssistant

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: sharanya.gandla05@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
  # footer:
  #   recentPosts: false
  #   socialNetworks:
  #     github: https://github.com/sharanya510
  #     linkedin: https://www.linkedin.com/in/sharanya-gandla-4097a7188/
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/sharanya510
      linkedin: https://www.linkedin.com/in/sharanya-gandla-4097a7188/

  # List pages like blogs and posts
  # listPages:
  #   disableFeaturedImage: false

  # Single pages like blog and post
  # singlePages:
  #   readTime:
  #     enable: true
  #     content: "min read"
  #   scrollprogress:
  #     enable: true

  # For translations
  # terms:
  #   read: "Read"
  #   toc: "Table Of Contents"
  #   copyright: "All rights reserved"
  #   pageNotFound: "Page not found"
  #   emailText: "Check out this site"

  # datesFormat:
  #   article: "Jan 2, 2006"
  #   articleList: "Jan 2, 2006"
  #   articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>