baseURL: "https://sharanya510.github.io"
languageCode: "en-us"
title: "Sharanya Gandla"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true


markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # title: "Hugo Profile"
  # description: Text about my cool site
  # # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  # useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  # animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"

  # If you want to customize the menu, you can change it here
  navbar:
    position: absolute
    # align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: null  # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    disableSearch: true
    # # searchPlaceholder: "Search"
    # menus:
    #   disableAbout: false
    #   disableExperience: false
    #   disableEducation: false
    #   disableProjects: false
    #   disableAchievements: false
    #   disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi there! I am "
    title: "Sharanya Gandla."
    subtitle: "Graduate student at San Jose State University"
    content: "A passionate graduate student who loves exploring latest technologies, building POCs and incorporating them into existing products.
    I really enjoy painting, baking and photography.
    I live in San Jose, California, USA."
    image: "/images/sharanya3.png"
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/1kOaq68eZ6v41QoWYWeYSsn9Sb3jKgBn9/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/sharanya510
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/sharanya-gandla-4097a7188/
        

  # About
  about:
    enable: true
    title: "About"
    image: "/images/sharanya1.png"
    content: |-
     Currently looking for Full-time opportunities. Pursuing master's degree in Data Science with 2.5 years of professional experience as a Software Engineer at NCR Corporation, Hyderabad, India. 
     Seeking to work at the intersection of Technology and Business.
     
    skills:
      enable: true
      title: "Skills"
      items:
        - "Framework & Libraries: React, NodeJS, Flask, Express"
        - "Databases: MySQL, MongoDB, PostgreSQL, Elasticsearch"
        - "Networking: RESTful API, HTTP, Nginx"
        - "Enterprise Tools: Logstash, Kibana, Grafana, Apache Kafka, Postman, Prometheus"
        - "Programming Languages: C, C++, Python, GO, HTML, CSS, Powershell, Bash, Unix/Linux, Javascript"
        - "Certifications: AZ-900 Microsoft Fundamentals, Getting Started with GKE by Coursera, GCP by coursera"
        - "Machine Learning Tools: Pandas, Numpy, TensorFlow, PyTorch, TensorFlow Serving, Sci-Kit learn, Keras"
        - "Cloud Technologies,Cloud Native and DevOps: AWS, Azure, GCP, Git, Jenkins, Chef, Terraform, Docker, Kubernetes, Sensu, Site 24x7, Apigee, Rundeck, Helm, Vault, Git, GitHub Actions, BitBucket, Matlab, Tableau, Artifactory, ArgoCD"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Software Engineer II"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "Feb 2021 - Dec 2021"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Led and managed the “Chef Upgrade” project, migrated all cookbooks from Chef version 14 to 17.
          - Spearheaded the “Migration from ARM to Terraform” initiative across 6 products, resulting in increasing flexibility for deployment.
          - Deployed automation for globally patching and booting virtual machines on the Azure cloud using azure automation account, leading to a reduction of approximately 16 hours per week in time expended by the cloud team.
          - Led and contributed to the development of client-server RESTful endpoints for NOLO, supporting the implementation of new features.
          - Enhanced the NOLO product's performance, scalability, availability, and reliability during peak hours and Super Bowl events by implementing infrastructure improvements. Ensured compliance with SLAs to prevent any issues.

      - job: "Software Engineer I"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "July 2019 - Jan 2021"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Devised and put into practice an extensive process leveraging Apigee and GitHub Actions to manage traffic throughout the “Migration from on-premise to Azure” project.
          - Utilized sensu monitoring tool with helm across 10 products, performing version control mechanism revamped efficiency by 20%.
          - Facilitated data retrieval for developers by executing select queries on databases, subsequently streamlining the process through a PowerShell script. Designed and executed updates to database schemas, models, queries for improving data management efficiency.
          - Created container Images using Docker, registry management, container orchestration, demonstrated by successfully writing, pushing, and testing images on Docker Hub, and Azure Container Registry for efficient application deployment.
          - Migrated all repositories from Jenkins to GitHub Actions, utilizes YAML for defining workflows, leading to faster builds and deployments.
          - Containerized an online ordering product (NOLO) and Implemented the rolling update strategy in Kubernetes to enable seamless updates of the NOLO application without causing any downtime.

      - job: "Software Engineer Intern"
        company: "NCR Corporation"
        companyUrl: "https://ncr.com"
        date: "May 2019 - June 2019"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Setup monitoring for multiple products using Site 24x7, Sensu and Prometheus. Built customized dashboards with Application Insights to monitor application performance during high traffic periods.
          - For visualization, I used Grafana, Kibana. These dashboards increased visibility and allowed for proactive troubleshooting.


      - job: "Software Trainee"
        company: "CDAC"
        companyUrl: "https://ncr.com"
        date: "Jan 2019 - April 2019"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - Underwent a 10 week training program on software technologies like C, C++, DS, DBMS, SQL, windows, HTML, XML.

      - job: "Intern"
        company: "NFC"
        # companyUrl: "https://.com"
        date: "June 2018 - June 2018"
        info:
          enable: true
          content: "Location: Hyderabad, India "
        content: |
          Hyderabad, India
          - One month internship program, where I have obtained great exposure towards the processes carried out at NFC and understanding of how do they actually make use of chemicals.
          - It was a wonderful opportunity to work on aproject titled "Monitoring temperature and humidity in a room" and gained practical exposure.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science"
        school:
          name: "San Jose State University"
          url: "https://sjsu.org"
        date: "2022 - 2023"
        GPA: "3.75 out of 4.0"
        content: |-
          Course Work
            - Data Structures & Algorithms
            - Data Mining
            - Enterprise Software Platforms
            - Business Intelligence Systems
            - AI and Data Engineering

      - title: "Bachelor of Engineering in Electronics and Communication"
        school:
          name: "Chaitanya Bharathi Institute of Technology"
          url: "https://cbit.org"
        date: "2015 - 2019"
        GPA: "9.2 out of 10.0"
        content: |-
          Extracurricular Activities
            - Been head of the Design team for the college fest over the period of 4 years.
            - Won multiple prizes in the art competition.
            

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: R&D Excellence award
        content: I was awarded R&D excellence award for the year 2020 for my work on the project Nolo Traffic Manager.
        
     

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Acceleration via Intel Optimization for PyTorch
        content: Demonstrated substantial performance improvement in “resnet50” image classification on the “Fashion MNIST” dataset by accelerating via Intel Optimization for PyTorch and Torchscript. Accomplished an impressive 94.6% reduction in models inference time. Effectively visualized the models performance logs on TensorBoard for comprehensive analysis.
        image: /images/acceleration.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/Acceleration_via_intel_optimization_for_pytorch

      - title: Twitter Sentiment Analysis
        content: Performed Sentiment Analysis with NLP where live tweets are extracted using Twitter API and pre-processed the tweets to classify tweets as positive, negative, and neutral with an LSTM model.
        image: /images/twitter.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/Twitter-sentiment-analysis

      - title: Multi Modal Classifier
        content: Developed a sequential multi-modal deep learning classifier utilizing the Fashion MNIST dataset, achieving a 91.72% accuracy. Successfully transformed the TensorFlow model into TensorFlow Lite format for optimized deployment and conducted inference. Implemented model serving using TensorFlow serving to ensure efficient and reliable predictions.
        image: /images/multimodal.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/MultiModalClassifier

      - title: House Price Prediction
        content: Constructed a regression model with the capability to precisely predict property rices through an analysis of their attributes. This process entailed comprehending the dataset, conducting Exploratory Data Analysis(EDA), crafting a Flask web application, and executing its deployment.
        image: /images/house.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/House_Price_Prediction
      
      - title: Mirror Assistant
        content: An application that will assess your spoken words, hand gestures, and facial expressions, providing immediate feedback and delivering a comprehensive summary of your performance once you deliver a speech. Performed comprehensive background analysis by utilizing OpenCV, TensorFlow, Google Cloud’s Speech-to-text API and implemented Flask for the Backend. For the Frontend, used ReactJS and incorporated the Formidable Victory Library to display real-time data visualizations.
        image: /images/mirror.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/MirrorAssistant
          
      - title: Smart Meter Management System
        content: Developed a full-stack web app using MongoDB, NodeJS, ExpressJS serving as a RESTful API with React as Frontend. Deployed Backend server on Heroku.  Generates bills in a building based on a pay-as-you-use model.
        image: /images/smartmeter.png
        links:
          - icon: fab fa-github
            url: https://github.com/Sharanya510/SmartMeterManagementSystem

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: sharanya.gandla05@gmail.com
    btnName: Mail me

    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
  # footer:
  #   recentPosts: false
  #   socialNetworks:
  #     github: https://github.com/sharanya510
  #     linkedin: https://www.linkedin.com/in/sharanya-gandla-4097a7188/
  
  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/sharanya510
      linkedin: https://www.linkedin.com/in/sharanya-gandla-4097a7188/

  # List pages like blogs and posts
  # listPages:
  #   disableFeaturedImage: false

  # Single pages like blog and post
  # singlePages:
  #   readTime:
  #     enable: true
  #     content: "min read"
  #   scrollprogress:
  #     enable: true

  # For translations
  # terms:
  #   read: "Read"
  #   toc: "Table Of Contents"
  #   copyright: "All rights reserved"
  #   pageNotFound: "Page not found"
  #   emailText: "Check out this site"

  # datesFormat:
  #   article: "Jan 2, 2006"
  #   articleList: "Jan 2, 2006"
  #   articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>